### ISSUE TITLE
TypeError - no implicit conversion of true into Hash:

### ISSUE THREAD

**Issue by harssh** [socialpandas/sidekiq_monitor#25]
I get this error in rails console after below query  and UI is coming blank
<code>
Sidekiq::Monitor::Job Load (1.3ms)  SELECT  `sidekiq_jobs`.\* FROM `sidekiq_jobs`  WHERE `sidekiq_jobs`.`queue` = 'legacy_importer'  ORDER BY sidekiq_jobs.enqueued_at DESC LIMIT 10 OFFSET 0 Completed 500 Internal Server Error in 16ms  
TypeError - no implicit conversion of true into Hash:
</code>
My worker has this code at the end 

{
        message: "#{users.count} users processed"
}

Output of Sidekiq::Monitor::Job.all in rails console 

  "Sidekiq::Monitor::Job.all
  Sidekiq::Monitor::Job Load (0.4ms)  SELECT `sidekiq_jobs`.\* FROM `sidekiq_jobs`

Sidekiq::Monitor::Job id: 3, jid: "f8f21eba5547390451721801", queue: "legacy_importer", class_name: "LegacyUserWorker", args: [], retry: true, enqueued_at: "2014-06-17 12:33:04", started_at: "2014-06-17 12:34:38", finished_at: "2014-06-17 12:34:45", status: "complete", name: nil, result: {:message=>"526 users processed"}

**Comment by harssh** [comment]
https://github.com/harssh/sidekiq_monitor/commit/b4b2602b44073b79d4d78f218242ea451b970dba

Removing true from distance_of_time_in_words method solved the problem.

Using rails 4 ruby 2.1

http://api.rubyonrails.org/classes/ActionView/Helpers/DateHelper.html#method-i-distance_of_time_in_words 

api docs doesn't seem to have only true but should have a option like "include_seconds: true"
example: distance_of_time_in_words(from_time, to_time, include_seconds: true)

**Comment by abrambailey** [comment]
Using sidekiq_monitor (0.1.4) I am experiencing the same issue. 

```
2.1.2 :018 > Sidekiq::Monitor::Job.all
  Sidekiq::Monitor::Job Load (0.4ms)  SELECT `sidekiq_jobs`.* FROM `sidekiq_jobs`
 => #<ActiveRecord::Relation [#<Sidekiq::Monitor::Job id: 6, jid: "5d9cc837d15b2b0b24b2b88d", queue: "default", class_name: "HardWorker", args: ["bob", 6], retry: true, enqueued_at: "2014-07-20 20:35:11", started_at: "2014-07-20 20:35:11", finished_at: "2014-07-20 20:35:11", status: "complete", name: nil, result: nil>]> 

Started GET "/sidekiq/api/jobs?sEcho=2&iColumns=12&sColumns=&iDisplayStart=0&iDisplayLength=10&mDataProp_0=0&mDataProp_1=1&mDataProp_2=2&mDataProp_3=3&mDataProp_4=4&mDataProp_5=5&mDataProp_6=6&mDataProp_7=7&mDataProp_8=8&mDataProp_9=9&mDataProp_10=10&mDataProp_11=11&sSearch=&bRegex=false&sSearch_0=&bRegex_0=false&bSearchable_0=true&sSearch_1=&bRegex_1=false&bSearchable_1=true&sSearch_2=&bRegex_2=false&bSearchable_2=true&sSearch_3=&bRegex_3=false&bSearchable_3=true&sSearch_4=&bRegex_4=false&bSearchable_4=true&sSearch_5=&bRegex_5=false&bSearchable_5=true&sSearch_6=&bRegex_6=false&bSearchable_6=true&sSearch_7=&bRegex_7=false&bSearchable_7=true&sSearch_8=&bRegex_8=false&bSearchable_8=true&sSearch_9=&bRegex_9=false&bSearchable_9=true&sSearch_10=&bRegex_10=false&bSearchable_10=true&sSearch_11=&bRegex_11=false&bSearchable_11=true&iSortCol_0=5&sSortDir_0=desc&iSortingCols=1&bSortable_0=true&bSortable_1=true&bSortable_2=true&bSortable_3=true&bSortable_4=false&bSortable_5=true&bSortable_6=true&bSortable_7=true&bSortable_8=false&bSortable_9=true&bSortable_10=true&bSortable_11=true&queue=default" for 127.0.0.1 at 2014-07-20 15:21:36 -0500
Processing by Sidekiq::Monitor::Api::JobsController#index as JSON
  Parameters: {"sEcho"=>"2", "iColumns"=>"12", "sColumns"=>"", "iDisplayStart"=>"0", "iDisplayLength"=>"10", "mDataProp_0"=>"0", "mDataProp_1"=>"1", "mDataProp_2"=>"2", "mDataProp_3"=>"3", "mDataProp_4"=>"4", "mDataProp_5"=>"5", "mDataProp_6"=>"6", "mDataProp_7"=>"7", "mDataProp_8"=>"8", "mDataProp_9"=>"9", "mDataProp_10"=>"10", "mDataProp_11"=>"11", "sSearch"=>"", "bRegex"=>"false", "sSearch_0"=>"", "bRegex_0"=>"false", "bSearchable_0"=>"true", "sSearch_1"=>"", "bRegex_1"=>"false", "bSearchable_1"=>"true", "sSearch_2"=>"", "bRegex_2"=>"false", "bSearchable_2"=>"true", "sSearch_3"=>"", "bRegex_3"=>"false", "bSearchable_3"=>"true", "sSearch_4"=>"", "bRegex_4"=>"false", "bSearchable_4"=>"true", "sSearch_5"=>"", "bRegex_5"=>"false", "bSearchable_5"=>"true", "sSearch_6"=>"", "bRegex_6"=>"false", "bSearchable_6"=>"true", "sSearch_7"=>"", "bRegex_7"=>"false", "bSearchable_7"=>"true", "sSearch_8"=>"", "bRegex_8"=>"false", "bSearchable_8"=>"true", "sSearch_9"=>"", "bRegex_9"=>"false", "bSearchable_9"=>"true", "sSearch_10"=>"", "bRegex_10"=>"false", "bSearchable_10"=>"true", "sSearch_11"=>"", "bRegex_11"=>"false", "bSearchable_11"=>"true", "iSortCol_0"=>"5", "sSortDir_0"=>"desc", "iSortingCols"=>"1", "bSortable_0"=>"true", "bSortable_1"=>"true", "bSortable_2"=>"true", "bSortable_3"=>"true", "bSortable_4"=>"false", "bSortable_5"=>"true", "bSortable_6"=>"true", "bSortable_7"=>"true", "bSortable_8"=>"false", "bSortable_9"=>"true", "bSortable_10"=>"true", "bSortable_11"=>"true", "queue"=>"default"}
   (0.3ms)  SELECT COUNT(*) FROM `sidekiq_jobs`
   (0.4ms)  SELECT COUNT(*) FROM `sidekiq_jobs`  WHERE `sidekiq_jobs`.`queue` = 'default'
  Sidekiq::Monitor::Job Load (0.2ms)  SELECT  `sidekiq_jobs`.* FROM `sidekiq_jobs`  WHERE `sidekiq_jobs`.`queue` = 'default'  ORDER BY sidekiq_jobs.enqueued_at DESC LIMIT 10 OFFSET 0
Completed 500 Internal Server Error in 20ms

TypeError - no implicit conversion of true into Hash:
  actionview (4.1.4) lib/action_view/helpers/date_helper.rb:70:in `distance_of_time_in_words'
  sidekiq_monitor (0.1.4) app/datatables/sidekiq/monitor/jobs_datatable.rb:82:in `simplified_distance_of_time_in_words'
  sidekiq_monitor (0.1.4) app/datatables/sidekiq/monitor/jobs_datatable.rb:76:in `get_duration'
  sidekiq_monitor (0.1.4) app/datatables/sidekiq/monitor/jobs_datatable.rb:54:in `block in data'
  activerecord (4.1.4) lib/active_record/relation/delegation.rb:46:in `map'
  sidekiq_monitor (0.1.4) app/datatables/sidekiq/monitor/jobs_datatable.rb:45:in `data'
  rails-datatables (0.0.2) lib/rails-datatables.rb:24:in `as_json'
  activesupport (4.1.4) lib/active_support/json/encoding.rb:34:in `encode'
  activesupport (4.1.4) lib/active_support/json/encoding.rb:21:in `encode'
  activesupport (4.1.4) lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
  actionpack (4.1.4) lib/action_controller/metal/renderers.rb:96:in `block in <module:Renderers>'
  active_model_serializers (0.8.1) lib/action_controller/serialization.rb:48:in `_render_option_json'
  actionpack (4.1.4) lib/action_controller/metal/renderers.rb:39:in `block in _handle_render_options'
  /home/funk/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/set.rb:263:in `each'
  actionpack (4.1.4) lib/action_controller/metal/renderers.rb:36:in `_handle_render_options'
  actionpack (4.1.4) lib/action_controller/metal/renderers.rb:32:in `render_to_body'
  actionpack (4.1.4) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.1.4) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.1.4) lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
  activesupport (4.1.4) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /home/funk/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
  activesupport (4.1.4) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.1.4) lib/action_controller/metal/instrumentation.rb:41:in `block in render'
  actionpack (4.1.4) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
  activerecord (4.1.4) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  sunspot_rails (2.1.1) lib/sunspot/rails/railties/controller_runtime.rb:15:in `cleanup_view_runtime'
  actionpack (4.1.4) lib/action_controller/metal/instrumentation.rb:40:in `render'
  sidekiq_monitor (0.1.4) app/controllers/sidekiq/monitor/api/jobs_controller.rb:8:in `index'
  actionpack (4.1.4) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.1.4) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.1.4) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.1.4) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.1.4) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.4) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.4) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.4) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.4) lib/active_support/callbacks.rb:86:in `run_callbacks'
  actionpack (4.1.4) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.4) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.1.4) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.1.4) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.4) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.4) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.1.4) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.1.4) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.1.4) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.1.4) lib/abstract_controller/base.rb:136:in `process'
  actionview (4.1.4) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.1.4) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.1.4) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.1.4) lib/action_controller/metal.rb:232:in `block in action'
  actionpack (4.1.4) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  actionpack (4.1.4) lib/action_dispatch/routing/route_set.rb:50:in `call'
  actionpack (4.1.4) lib/action_dispatch/journey/router.rb:71:in `block in call'
  actionpack (4.1.4) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.4) lib/action_dispatch/routing/route_set.rb:678:in `call'
  railties (4.1.4) lib/rails/engine.rb:514:in `call'
  railties (4.1.4) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.1.4) lib/action_dispatch/journey/router.rb:71:in `block in call'
  actionpack (4.1.4) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.4) lib/action_dispatch/routing/route_set.rb:678:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  xray-rails (0.1.14) lib/xray/middleware.rb:37:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  meta_request (0.3.3) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack-contrib (1.1.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.3.3) lib/meta_request/middlewares/headers.rb:16:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  meta_request (0.3.3) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/rack/error_collector.rb:50:in `traced_call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/rack/agent_hooks.rb:26:in `traced_call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/rack/browser_monitoring.rb:19:in `traced_call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/rack/developer_mode.rb:48:in `traced_call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.1.4) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.1.4) lib/action_dispatch/middleware/flash.rb:254:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.1.4) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  activerecord (4.1.4) lib/active_record/query_cache.rb:36:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  activerecord (4.1.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.1.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.4) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.4) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.1.4) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.1.4) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:56:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.1.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  railties (4.1.4) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.4) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.4) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.4) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.4) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.0.3) lib/quiet_assets.rb:23:in `call_with_quiet_assets'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.1.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  activesupport (4.1.4) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.1.4) lib/action_dispatch/middleware/static.rb:64:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  railties (4.1.4) lib/rails/engine.rb:514:in `call'
  railties (4.1.4) lib/rails/application.rb:144:in `call'
  railties (4.1.4) lib/rails/railtie.rb:194:in `method_missing'
  newrelic_rpm (3.9.0.229) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
  thin (1.6.2) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.2) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.2) lib/thin/connection.rb:53:in `process'
  thin (1.6.2) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.3) lib/eventmachine.rb:187:in `run'
  thin (1.6.2) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.2) lib/thin/server.rb:162:in `start'
  rack (1.5.2) lib/rack/handler/thin.rb:16:in `run'
  rack (1.5.2) lib/rack/server.rb:264:in `start'
  railties (4.1.4) lib/rails/commands/server.rb:69:in `start'
  railties (4.1.4) lib/rails/commands/commands_tasks.rb:81:in `block in server'
  railties (4.1.4) lib/rails/commands/commands_tasks.rb:76:in `server'
  railties (4.1.4) lib/rails/commands/commands_tasks.rb:40:in `run_command!'
  railties (4.1.4) lib/rails/commands.rb:17:in `<top (required)>'
  script/rails:6:in `<main>'
```

**Comment by harssh** [comment]
I have a pull request that solves this issue ........
Its not merged yet ..

**Comment by harssh** [comment]
https://github.com/socialpandas/sidekiq_monitor/pull/26

**Comment by abrambailey** [comment]
Is this it? https://github.com/harssh/sidekiq_monitor

**Comment by harssh** [comment]
yep

**Comment by abrambailey** [comment]
Thx
